### ISSUE TITLE
Features/Roadmap

### ISSUE THREAD

**Issue by WolfDan** [OkamiIO/Nomure#1]
# Features/RoadMap

An issue describing short and long term features as well the roadmap

- [ ] Property Values
    - [x] ~~I18N Strings~~ (for this we need string indexing etc... To really have sense, otherwise is just a property with and @ and the language at the end)
    - [ ] Primitive types List
    - [x] ~~Enums~~ (Is just a string, we do not check types)
    - [x] ~~Dictionary~~ (Use a node)

- [ ] Index
    - [ ] Datetime
    - [ ] List
    - [x] String
    - [x] Integer
    - [x] Float
    - [x] ~~Dictionary~~ (Use a node)

- [ ] Node implementation
    - [x] Set data
    - [ ] Get data
    - [x] Index property edges
    - [x] Inverse Node support `(relation.uid, "edge_name", node.uid) = node_relation_edge.uid`
    - [ ] Update
    - [ ] Delete 

- [ ] Edge implementation
    - [x] Set data
    - [ ] Get data
    - [ ] Index property edges
    - [ ] Update
    - [ ] Delete

- [ ] Query support

    - [ ] Query recursion
        A child node can query a parent node, this have a couple of problems, one is an infinite loop, the other is quering data to the database from an already queried node, I need to avoid that

    - [ ] `where` 
        - [ ] Datetime storage `{ year, month, day, seconds }`
        - [ ] `>` `KeySelector.first_greater_than(key)`
        - [ ] `<` `KeySelector.last_less_than(key)`
        - [ ] `==` `get_by_function(property, value, function = Function.equal)`
        - [ ] `>=` `KeySelector.first_greater_or_equal(key)`
        - [ ] `<=` `KeySelector.last_less_or_equal(key)`
        - [ ] `and`
        - [ ] `or`

    - [ ] `where_string`
        - [ ] `starts_with` serialize the string a tuple and set as a key, and use key selector for it (expensive)

    - [ ] pagination support (cursor based)
        - [ ] `after` `Transaction.get_range(after_cursor, end, limit)`
        - [ ] `before` `Transaction.get_range(before_cursor, end, limit, reverse=True)`
        - [ ] `limit`
        - [ ] `first` `Transaction.get_range(start, end, limit=first)`
        - [ ] `count`

    - [ ] sorting
        - [ ] `order_asc` 
        - [ ] `order_des`

    - [ ] reverse node

    - [ ] functions
        - [ ] `min` `Transaction.get_range(start, end, limit=1, reverse=True)`
        - [ ] `max` `Transaction.get_range(start, end, limit=1)`

    - [ ] query optimization, what most databases does, optimize the queries for a better performance

- [x] ~~Network Protocol implementation~~ (Maybe in a long term roadmap)
    - [ ] ~~GraphQL (standard query, mutation language) [this uses the connection 
    features of GraphQL to make it easier to query graph data]~~
    - [ ] ~~Opengraph (complex query for things like recommendation engines etc)~~

- [ ] More tests

- [x] Ztandart data compression

    Compress long sized strings in order to save space, _unnoticeable performance impact_
